[package]
name = "pulse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
heed = "0.20.5"
tokio = { version = "1.40.0", features = ["full"] }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false

